BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

LAYERSERIES_COMPAT_nxp-connectivity-examples = "styhead walnascar whinlatter wrynose"

IMAGE_INSTALL:append = " zigbee-coordinator matter-ncp "
IMAGE_INSTALL:append = " ${@bb.utils.contains_any('TUNE_FEATURES', 'armv8 armv8a', 'easymesh', '', d)} "

BBFILE_COLLECTIONS += "nxp-connectivity-examples"
BBFILE_PATTERN_nxp-connectivity-examples = "^${LAYERDIR}/"
BBFILE_PRIORITY_nxp-connectivity-examples = "7"
