FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx93evk imx93evk-iwxxx-matter", 'file://uboot-config/0001-imx93-11x11-evk-ffu-gpio-irq-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx91evk imx91evk-iwxxx-matter", 'file://uboot-config/0001-imx91-11x11-evk-ffu-gpio-irq-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx91qsb-iwxxx-matter", 'file://uboot-config/0001-imx91-9X9-qsb-ffu-gpio-irq-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx91frdm-iwxxx-matter", 'file://uboot-config/0001-imx91-11x11-frdm-ffu-gpio-irq-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx91s-frdm-iwxxx-matter", 'file://uboot-config/0001-imx91-11x11-frdm-imx91s-IW610-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx95-15x15-evk-iwxxx-matter", 'file://uboot-config/0001-imx95-15x15-evk-ffu_gpio_irq.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx8mpfrdm-iwxxx-matter", 'file://uboot-config/0001-imx8mp-frdm-ffu-gpio-irq-dtb.cfg', '', d)}"
SRC_URI += "${@bb.utils.contains_any('MACHINE', "imx95-frdm-pro-iwxxx-matter", 'file://uboot-config/0001-imx95-19x19-frdm-pro-iw612-dtb.cfg', '', d)}"