#@TYPE: Machine
#@NAME: i.MX8ULP EVK Matter
#@SOC: i.MX8ULP
#@MAINTAINER: Haoran Wang <elven.wang@nxp.com>

require conf/machine/imx8ulpevk.conf

UBOOT_DELTA_CONFIG = "${UNPACKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr packagegroup-nxp-zigbee-rcp docker-moby "

# Set to true to enable EdgeLock Enclave
USE_ELE = "true"
