#@TYPE: Machine
#@NAME: i.MX 95 15x15 lpddr4x frdm Consolidated Machine For Matter
#@DESCRIPTION: A consolidated machine for FRDM i.MX 95 15x15 lpddr4x Matter demos
#@MAINTAINER: Junmeng Li <junmeng.li_1@nxp.com>

MACHINEOVERRIDES =. "imx95-15x15-lpddr4x-frdm.conf:"
require conf/machine/imx95-15x15-lpddr4x-frdm.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
    freescale/imx95-15x15-frdm-iw612.dtb \
"

DTS_FILE = "${BSPDIR}/sources/meta-nxp-connectivity/meta-nxp-otbr/recipes-kernel/linux/files/dts/imx95-15x15-frdm-iw612.dts"

UBOOT_DELTA_CONFIG = "${UNPACKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr packagegroup-nxp-zigbee-rcp docker-moby "

# Set to true to enable EdgeLock Enclave
USE_ELE = "true"

# Indicates the machine supports IWxxx modules
MACHINE_FEATURES += "has-iwxxx"