#@TYPE: Machine
#@NAME: A consolidated IW612 MATTER machine for i.MX 91 EVK
#@SOC: i.MX91
#@MAINTAINER: Junmeng Li <junmeng.li_1@nxp.com>

MACHINEOVERRIDES =. "imx91-9x9-lpddr4-qsb:"
require conf/machine/imx91-9x9-lpddr4-qsb.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx91-9x9-qsb-lpuart5-bt-m2-3000000-ffu-gpio-irq.dtb \
"
DTS_FILE="${BSPDIR}/sources/meta-nxp-connectivity/meta-nxp-otbr/recipes-kernel/linux/files/dts/imx91-9x9-qsb-lpuart5-bt-m2-3000000-ffu-gpio-irq.dts"

UBOOT_DELTA_CONFIG="${UNPACKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr docker-moby "

# Set to true to enable EdgeLock Enclave
USE_ELE = "true"

# Indicates the machine supports IWxxx modules
MACHINE_FEATURES += "has-iwxxx"

MACHINE_FIRMWARE:append = " firmware-nxp-wifi-nxpiw610-sdio"
