#@TYPE: Machine
#@NAME: i.MX 95 19x19 lpddr5 frdm pro Consolidated Machine For Matter
#@DESCRIPTION: A consolidated machine for i.MX 95 19x19 LPDDR5 EVK Matter demos
#@MAINTAINER: Haoran Wang <elven.wang@nxp.com>

MACHINEOVERRIDES =. "imx95-19x19-lpddr5-frdm-pro.conf:"
require conf/machine/imx95-19x19-lpddr5-frdm-pro.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
    freescale/imx95-19x19-frdm-pro-iw612.dtb \
"

DTS_FILE = "${BSPDIR}/sources/meta-nxp-connectivity/meta-nxp-otbr/recipes-kernel/linux/files/dts/imx95-19x19-frdm-pro-iw612.dts"

UBOOT_DELTA_CONFIG = "${UNPACKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr packagegroup-nxp-zigbee-rcp docker-moby "

# Set to true to enable EdgeLock Enclave
USE_ELE = "true"

# Indicates the machine supports IWxxx modules
MACHINE_FEATURES += "has-iwxxx"