#@TYPE: Machine
#@NAME: A consolidated IW610 MATTER machine for i.MX 91 FRDM
#@SOC: i.MX91
#@MAINTAINER: Haoran Wang <elven.wang@nxp.com>

MACHINEOVERRIDES =. "imx91-11x11-lpddr4-evk:"
require conf/machine/imx91-11x11-lpddr4-evk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
    freescale/imx91-11x11-frdm-iw610.dtb \
"
UBOOT_CONFIG_BASENAME = "imx91_11x11_frdm"
#UBOOT_CONFIG[nand] = "${UBOOT_CONFIG_BASENAME}_spinand_defconfig"
#UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
#UBOOT_CONFIG[ecc] = "${UBOOT_CONFIG_BASENAME}_inline_ecc_defconfig"
DTS_FILE="${BSPDIR}/sources/meta-nxp-connectivity/meta-nxp-otbr/recipes-kernel/linux/files/dts/imx91-11x11-frdm-iw610.dts"

UBOOT_DELTA_CONFIG="${UNPACKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr docker-moby "

# Set to true to enable EdgeLock Encalve
USE_ELE = "true"

# Indicates the machine supports IWxxx modules
MACHINE_FEATURES += "has-iwxxx"

# Set the rootfs size since the eMMC size limit for imx91frdm
IMAGE_ROOTFS_SIZE:imx91frdm-iwxxx-matter = "5242880"
